### ISSUE TITLE
Homing missiles cause game to crash

### ISSUE THREAD

**Issue by samuelkurtdavidson** [ofaura/Andro_Dunos#4]
### Summary
- Which is the bug:  Game crashes
- Type of the bug: A
- Severity of the bug: High priority

***

### Behavior
- Expected behavior: missile should go down
- Actual behavior: game crashes when there are no enemies on screen when you try to shoot

***

### Steps to reproduce the problem
- Steps to follow: having the missile upgrade, try and shoot when there are no enemies around

***

### Specifications
- Version of the build reproduced: 0.7
- OS where the build was reproduced: Windows 10

**Comment by GAPIntoTheGame** [comment]
It's fixed
